# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Chooseui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(60, 40, 521, 471))
        self.main_frame.setMinimumSize(QtCore.QSize(521, 431))
        self.main_frame.setStyleSheet("#main_frame{\n"
"border-image: url(:/icons/Morphing Rovers/Qt2Unity/icons/celestial.jpg);}\n"
"")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.Aufgabe2_btn = QtWidgets.QPushButton(self.main_frame)
        self.Aufgabe2_btn.setGeometry(QtCore.QRect(370, 340, 111, 51))
        self.Aufgabe2_btn.setStyleSheet("#Aufgabe2_btn{\n"
"    font: italic 14pt \"Cascadia Mono\";\n"
"    border:none;\n"
"    color: rgb(179, 179, 179);\n"
"}\n"
"#Aufgabe2_btn:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.Aufgabe2_btn.setObjectName("Aufgabe2_btn")
        self.label = QtWidgets.QLabel(self.main_frame)
        self.label.setGeometry(QtCore.QRect(30, 20, 231, 61))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Agency FB\";\n"
"font: italic 12pt \"Californian FB\";\n"
"font: 18pt \"Californian FB\";")
        self.label.setObjectName("label")
        self.close_btn = QtWidgets.QPushButton(self.main_frame)
        self.close_btn.setGeometry(QtCore.QRect(480, 10, 31, 31))
        self.close_btn.setStyleSheet("#close_btn{\n"
"    border-image: url(:/icons/Morphing Rovers/Qt2Unity/icons/close.webp);\n"
"}\n"
"#close_btn:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.close_btn.setText("")
        self.close_btn.setObjectName("close_btn")
        self.Aufgabe1_btn = QtWidgets.QPushButton(self.main_frame)
        self.Aufgabe1_btn.setGeometry(QtCore.QRect(60, 340, 111, 51))
        self.Aufgabe1_btn.setStyleSheet("#Aufgabe1_btn{\n"
"    font: italic 14pt \"Cascadia Mono\";\n"
"    border:none;\n"
"    color: rgb(179, 179, 179);\n"
"}\n"
"#Aufgabe1_btn:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.Aufgabe1_btn.setObjectName("Aufgabe1_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.close_btn.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Aufgabe2_btn.setText(_translate("MainWindow", "Aufgabe2"))
        self.label.setText(_translate("MainWindow", "Welcome Aboard"))
        self.Aufgabe1_btn.setText(_translate("MainWindow", "Aufgabe1"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
