# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Aufgabe1Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aufgabe1_MainWindow(object):
    def setupUi(self, Aufgabe1_MainWindow):
        Aufgabe1_MainWindow.setObjectName("Aufgabe1_MainWindow")
        Aufgabe1_MainWindow.resize(800, 607)
        self.centralwidget = QtWidgets.QWidget(Aufgabe1_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Aufgabe1_frame = QtWidgets.QFrame(self.centralwidget)
        self.Aufgabe1_frame.setEnabled(True)
        self.Aufgabe1_frame.setGeometry(QtCore.QRect(90, 40, 521, 471))
        self.Aufgabe1_frame.setMinimumSize(QtCore.QSize(521, 431))
        self.Aufgabe1_frame.setStyleSheet("#Aufgabe1_frame{\n"
"    border-image: url(:/bild/icons/earth.jpg);\n"
"}\n"
"")
        self.Aufgabe1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Aufgabe1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Aufgabe1_frame.setObjectName("Aufgabe1_frame")
        self.label = QtWidgets.QLabel(self.Aufgabe1_frame)
        self.label.setGeometry(QtCore.QRect(80, 230, 111, 51))
        self.label.setStyleSheet("font: 17pt \"Lucida Calligraphy\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.K_lineEdit = QtWidgets.QLineEdit(self.Aufgabe1_frame)
        self.K_lineEdit.setGeometry(QtCore.QRect(180, 230, 161, 51))
        self.K_lineEdit.setStyleSheet("QLineEdit{\n"
"    font: 23pt \"Lucida Calligraphy\";;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255,0);\n"
"    border:none;\n"
"    border-bottom:1px solid white;\n"
"}")
        self.K_lineEdit.setObjectName("K_lineEdit")
        self.label_2 = QtWidgets.QLabel(self.Aufgabe1_frame)
        self.label_2.setGeometry(QtCore.QRect(50, 310, 111, 51))
        self.label_2.setStyleSheet("font: 17pt \"Lucida Calligraphy\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.S_lineEdit = QtWidgets.QLineEdit(self.Aufgabe1_frame)
        self.S_lineEdit.setGeometry(QtCore.QRect(180, 310, 161, 51))
        self.S_lineEdit.setStyleSheet("QLineEdit{\n"
"    font: 23pt \"Lucida Calligraphy\";;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255,0);\n"
"    border:none;\n"
"    border-bottom:1px solid white;\n"
"}")
        self.S_lineEdit.setObjectName("S_lineEdit")
        self.sub_1 = QtWidgets.QPushButton(self.Aufgabe1_frame)
        self.sub_1.setEnabled(False)
        self.sub_1.setGeometry(QtCore.QRect(360, 300, 141, 51))
        self.sub_1.setStyleSheet("QPushButton{\n"
"    font: 13pt \"Lucida Calligraphy\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    font: 13pt \"Lucida Calligraphy\";\n"
"    color: rgba(255, 255, 255,0);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.sub_1.setObjectName("sub_1")
        self.pushButton = QtWidgets.QPushButton(self.Aufgabe1_frame)
        self.pushButton.setGeometry(QtCore.QRect(480, 20, 31, 31))
        self.pushButton.setStyleSheet("border-image: url(:/bild/icons/close.webp);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.Aufgabe1_back_btn = QtWidgets.QPushButton(self.Aufgabe1_frame)
        self.Aufgabe1_back_btn.setGeometry(QtCore.QRect(20, 20, 61, 51))
        self.Aufgabe1_back_btn.setStyleSheet("border-image: url(:/bild/icons/arrow.png);\n"
"")
        self.Aufgabe1_back_btn.setText("")
        self.Aufgabe1_back_btn.setObjectName("Aufgabe1_back_btn")
        Aufgabe1_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Aufgabe1_MainWindow)
        self.pushButton.clicked.connect(Aufgabe1_MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Aufgabe1_MainWindow)

    def retranslateUi(self, Aufgabe1_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Aufgabe1_MainWindow.setWindowTitle(_translate("Aufgabe1_MainWindow", "MainWindow"))
        self.label.setText(_translate("Aufgabe1_MainWindow", "Karte:"))
        self.label_2.setText(_translate("Aufgabe1_MainWindow", "Szenario:"))
        self.sub_1.setText(_translate("Aufgabe1_MainWindow", "Bestätigen"))
import res22_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Aufgabe1_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Aufgabe1_MainWindow()
    ui.setupUi(Aufgabe1_MainWindow)
    Aufgabe1_MainWindow.show()
    sys.exit(app.exec_())
