# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Aufgabe2Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aufgabe2_MainWindow(object):
    def setupUi(self, Aufgabe2_MainWindow):
        Aufgabe2_MainWindow.setObjectName("Aufgabe2_MainWindow")
        Aufgabe2_MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Aufgabe2_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Aufgabe2_frame = QtWidgets.QFrame(self.centralwidget)
        self.Aufgabe2_frame.setGeometry(QtCore.QRect(60, 40, 521, 471))
        self.Aufgabe2_frame.setMinimumSize(QtCore.QSize(521, 431))
        self.Aufgabe2_frame.setStyleSheet("#Aufgabe2_frame{\n"
"    border-image: url(:/bg/icons/earth.jpg);\n"
"}")
        self.Aufgabe2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Aufgabe2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Aufgabe2_frame.setObjectName("Aufgabe2_frame")
        self.Aufgabe2_back_btn = QtWidgets.QPushButton(self.Aufgabe2_frame)
        self.Aufgabe2_back_btn.setGeometry(QtCore.QRect(20, 20, 61, 51))
        self.Aufgabe2_back_btn.setStyleSheet("border-image: url(:/bg/icons/arrow.png);")
        self.Aufgabe2_back_btn.setText("")
        self.Aufgabe2_back_btn.setObjectName("Aufgabe2_back_btn")
        self.pushButton = QtWidgets.QPushButton(self.Aufgabe2_frame)
        self.pushButton.setGeometry(QtCore.QRect(480, 20, 31, 31))
        self.pushButton.setStyleSheet("border-image: url(:/bg/icons/close.webp);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.sub_2 = QtWidgets.QPushButton(self.Aufgabe2_frame)
        self.sub_2.setEnabled(False)
        self.sub_2.setGeometry(QtCore.QRect(360, 300, 141, 51))
        self.sub_2.setStyleSheet("QPushButton{\n"
"    font: 13pt \"Lucida Calligraphy\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:disabled {\n"
"    font: 13pt \"Lucida Calligraphy\";\n"
"    color: rgba(255, 255, 255,0);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.sub_2.setObjectName("sub_2")
        self.Rover_btn = QtWidgets.QPushButton(self.Aufgabe2_frame)
        self.Rover_btn.setGeometry(QtCore.QRect(30, 130, 75, 23))
        self.Rover_btn.setStyleSheet("QPushButton{\n"
"    font: 15pt \"Lucida Calligraphy\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.Rover_btn.setCheckable(True)
        self.Rover_btn.setObjectName("Rover_btn")
        self.Probe_btn = QtWidgets.QPushButton(self.Aufgabe2_frame)
        self.Probe_btn.setGeometry(QtCore.QRect(30, 250, 75, 23))
        self.Probe_btn.setStyleSheet("QPushButton{\n"
"    font: 15pt \"Lucida Calligraphy\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}")
        self.Probe_btn.setCheckable(True)
        self.Probe_btn.setObjectName("Probe_btn")
        self.R_x_label = QtWidgets.QLabel(self.Aufgabe2_frame)
        self.R_x_label.setGeometry(QtCore.QRect(123, 131, 31, 21))
        self.R_x_label.setStyleSheet("font: 15pt \"Lucida Calligraphy\";\n"
"color: rgb(255, 255, 255);")
        self.R_x_label.setObjectName("R_x_label")
        self.R_y_label = QtWidgets.QLabel(self.Aufgabe2_frame)
        self.R_y_label.setGeometry(QtCore.QRect(123, 160, 31, 21))
        self.R_y_label.setStyleSheet("font: 15pt \"Lucida Calligraphy\";\n"
"color: rgb(255, 255, 255);")
        self.R_y_label.setObjectName("R_y_label")
        self.P_x_label = QtWidgets.QLabel(self.Aufgabe2_frame)
        self.P_x_label.setGeometry(QtCore.QRect(123, 250, 31, 21))
        self.P_x_label.setStyleSheet("font: 15pt \"Lucida Calligraphy\";\n"
"color: rgb(255, 255, 255);")
        self.P_x_label.setObjectName("P_x_label")
        self.P_y_label = QtWidgets.QLabel(self.Aufgabe2_frame)
        self.P_y_label.setGeometry(QtCore.QRect(123, 280, 31, 21))
        self.P_y_label.setStyleSheet("font: 15pt \"Lucida Calligraphy\";\n"
"color: rgb(255, 255, 255);")
        self.P_y_label.setObjectName("P_y_label")
        self.Rover_x = QtWidgets.QLineEdit(self.Aufgabe2_frame)
        self.Rover_x.setGeometry(QtCore.QRect(160, 130, 113, 20))
        self.Rover_x.setStyleSheet("QLineEdit{\n"
"    font: 20pt \"Lucida Calligraphy\";;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255,0);\n"
"    border:none;\n"
"    border-bottom:1px solid white;\n"
"}")
        self.Rover_x.setObjectName("Rover_x")
        self.Rover_y = QtWidgets.QLineEdit(self.Aufgabe2_frame)
        self.Rover_y.setGeometry(QtCore.QRect(160, 160, 113, 20))
        self.Rover_y.setStyleSheet("QLineEdit{\n"
"    font: 20pt \"Lucida Calligraphy\";;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255,0);\n"
"    border:none;\n"
"    border-bottom:1px solid white;\n"
"}")
        self.Rover_y.setObjectName("Rover_y")
        self.Probe_x = QtWidgets.QLineEdit(self.Aufgabe2_frame)
        self.Probe_x.setGeometry(QtCore.QRect(160, 250, 113, 20))
        self.Probe_x.setStyleSheet("QLineEdit{\n"
"    font: 20pt \"Lucida Calligraphy\";;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255,0);\n"
"    border:none;\n"
"    border-bottom:1px solid white;\n"
"}")
        self.Probe_x.setObjectName("Probe_x")
        self.Probe_y = QtWidgets.QLineEdit(self.Aufgabe2_frame)
        self.Probe_y.setGeometry(QtCore.QRect(160, 280, 113, 20))
        self.Probe_y.setStyleSheet("QLineEdit{\n"
"    font: 20pt \"Lucida Calligraphy\";;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255,0);\n"
"    border:none;\n"
"    border-bottom:1px solid white;\n"
"}")
        self.Probe_y.setObjectName("Probe_y")
        Aufgabe2_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Aufgabe2_MainWindow)
        self.pushButton.clicked.connect(Aufgabe2_MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Aufgabe2_MainWindow)

    def retranslateUi(self, Aufgabe2_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Aufgabe2_MainWindow.setWindowTitle(_translate("Aufgabe2_MainWindow", "MainWindow"))
        self.sub_2.setText(_translate("Aufgabe2_MainWindow", "Bestätigen"))
        self.Rover_btn.setText(_translate("Aufgabe2_MainWindow", "Rover"))
        self.Probe_btn.setText(_translate("Aufgabe2_MainWindow", "Probe"))
        self.R_x_label.setText(_translate("Aufgabe2_MainWindow", "X:"))
        self.R_y_label.setText(_translate("Aufgabe2_MainWindow", "Y:"))
        self.P_x_label.setText(_translate("Aufgabe2_MainWindow", "X:"))
        self.P_y_label.setText(_translate("Aufgabe2_MainWindow", "Y:"))
import res33_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Aufgabe2_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Aufgabe2_MainWindow()
    ui.setupUi(Aufgabe2_MainWindow)
    Aufgabe2_MainWindow.show()
    sys.exit(app.exec_())
